#!/usr/bin/env bash
set -eo pipefail

cd /workspace/baseline
source /opt/ros/humble/setup.bash
set -u

export PYTHONPATH="/workspace/baseline:/workspace/baseline/examples/supermarket_sorting:/workspace/baseline/examples/ros2:/opt/ros/humble/local/lib/python3.10/dist-packages:/opt/ros/humble/lib/python3.10/site-packages:${PYTHONPATH:-}"

export SUPERMARKET_ORDER="${SUPERMARKET_ORDER:-official}"
export SUPERMARKET_ALLOW_RUNTIME_LAYOUT="${SUPERMARKET_ALLOW_RUNTIME_LAYOUT:-0}"
export SUPERMARKET_ENABLE_AVOIDANCE="${SUPERMARKET_ENABLE_AVOIDANCE:-1}"
export SUPERMARKET_ENABLE_DEPTH_AVOIDANCE="${SUPERMARKET_ENABLE_DEPTH_AVOIDANCE:-1}"
export SUPERMARKET_SEARCH_DETECT_TIMEOUT="${SUPERMARKET_SEARCH_DETECT_TIMEOUT:-2.5}"
export SUPERMARKET_LOCAL_GRASP_RETRIES="${SUPERMARKET_LOCAL_GRASP_RETRIES:-3}"
export SUPERMARKET_DROP_RECOVERIES="${SUPERMARKET_DROP_RECOVERIES:-3}"
export SUPERMARKET_MAX_DELIVERY_RECOVERIES="${SUPERMARKET_MAX_DELIVERY_RECOVERIES:-8}"
export SUPERMARKET_DELIVERY_RECOVERY_COOLDOWN="${SUPERMARKET_DELIVERY_RECOVERY_COOLDOWN:-1.5}"
export SUPERMARKET_CARRY_TUCK_ENABLED="${SUPERMARKET_CARRY_TUCK_ENABLED:-1}"
export SUPERMARKET_DELIVERY_USE_ASTAR="${SUPERMARKET_DELIVERY_USE_ASTAR:-0}"

exec /usr/bin/python3 examples/supermarket_sorting/supermarket_sorting_decision_client.py
